export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const ADD_INGREDIENT_TO_BUILDER = "ADD_INGREDIENT_TO_BUILDER";

export const OPEN_INGREDIENTS_DETAILS_MODAL = "OPEN_INGREDIENTS_DETAILS_MODAL";
export const CLOSE_INGREDIENTS_DETAILS_MODAL = "CLOSE_INGREDIENTS_DETAILS_MODAL"; // prettier-ignore

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const UPDATE_ORDER_NUMBER = "UPDATE_ORDER_NUMBER";
